/**
 * Migration runner.
 *
 * Run with: `npm run db:migrate`
 *
 * Reads compiled SQL migrations from ./drizzle/ (generated by `npm run db:generate`)
 * and applies any that haven't been recorded yet.
 *
 * Safe to run repeatedly — Drizzle tracks applied migrations in its own table.
 * On Render, this is invoked as part of the deploy lifecycle (Pre-Deploy
 * Command) before the new server version starts handling traffic.
 */

import { drizzle } from 'drizzle-orm/postgres-js';
import { migrate } from 'drizzle-orm/postgres-js/migrator';
import postgres from 'postgres';
import { loadEnv } from '../lib/env.js';

async function main() {
  const env = loadEnv();

  const needsSsl =
    env.DATABASE_URL.includes('sslmode=require') ||
    env.DATABASE_URL.includes('render.com') ||
    env.NODE_ENV === 'production';

  // Migrator wants its own short-lived connection pool.
  const sql = postgres(env.DATABASE_URL, {
    ssl: needsSsl ? 'require' : false,
    max: 1,
  });
  const db = drizzle(sql);

  console.log('Running migrations...');
  await migrate(db, { migrationsFolder: './drizzle' });
  console.log('Migrations complete.');

  await sql.end();
}

main().catch((err) => {
  console.error('Migration failed:', err);
  process.exit(1);
});
